source "https://rubygems.org"

ruby "3.3.2"

gem "rails", "~> 7.1.3", ">= 7.1.3.4"
gem "puma", ">= 5.0"
gem "bcrypt", "~> 3.1", ">= 3.1.11"
gem "tzinfo-data", platforms: %i[windows jruby]
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'simplecov', require: false
end

gem 'mongoid'
gem 'active_model_serializers', '~> 0.10.0'
gem 'kaminari'

gem 'rswag'
gem 'rswag-api'
gem 'rswag-ui'
